// THIS FILE WAS AUTOMATICALLY GENERATED BY A TOOL
// Use `go generate` to generate this.

package funcmap

// FuncMap is the actual function map, where the key is the name of the
// functions, and the functions are those contained in this package.
var FuncMap = map[string]interface{}{
	"HTML": HTML,
	"Has": Has,
	"SystemSettings": SystemSettings,
	"Version": Version,
	"IsTFAEnabled": IsTFAEnabled,
	"BAnd": BAnd,
	"UnixNano": UnixNano,
	"CurrYear": CurrYear,
}
